name: generate snake

on:

  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: generate
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake.svg

      - name: push
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
